# This action is used to request a VLC frame from another robot for loop closure detection
# goal definition
uint32 robot_id
uint32 pose_id
---
# result definition
kimera_distributed/VLCFrameMsg frame
---
# feedback
bool active